version: '2'
services:
  docker_test:
    image: sd1620597/${JOB_NAME}:${TAG}
    ports: 
      - 8888:9090
    command: java -jar /usr/local/study_boot_demo-0.0.1-SNAPSHOT.jar --spring.profiles.active={PROFILE}
    build: .
